### ISSUE TITLE
error miner.py

### ISSUE THREAD

**Issue by KKK00** [cosme12/SimpleCoin#27]
i have this error when i run miner.py:
rocess Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "miner.py", line 97, in mine
    last_block = BLOCKCHAIN[len(BLOCKCHAIN) - 1]
TypeError: object of type 'bool' has no len()
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
^CTraceback (most recent call last):
  File "miner.py", line 269, in <module>
    p2 = Process(target=node.run(), args=b)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 80, in __init__
    self._args = tuple(args)
TypeError: 'Connection' object is not iterable

**Comment by rokasbalsys** [comment]
I am receiving same errors, don't know how to fix them

**Comment by cosme12** [comment]
It should be fixed now. Sorry for the delay.
