### ISSUE TITLE
error when trying to see transitions in windows

### ISSUE THREAD

**Issue by mehanalavimajd** [cosme12/SimpleCoin#68]
I wanted to see my own transitions but when I try it will give me :
```
C:\Users\mehan\Desktop\SimpleCoin\simpleCoin>python wallet.py
       =========================================

        SIMPLE COIN v1.0.0 - BLOCKCHAIN SYSTEM

       =========================================


        You can find more help at: https://github.com/cosme12/SimpleCoin

        Make sure you are using the latest version or you may end in
        a parallel chain.



What do you want to do?
        1. Generate new wallet
        2. Send coins to another wallet
        3. Check transactions
3
Traceback (most recent call last):
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 948, in send
    self.connect()
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001748EAAB610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /blocks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001748EAAB610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mehan\Desktop\SimpleCoin\simpleCoin\wallet.py", line 135, in <module>
    wallet()
  File "C:\Users\mehan\Desktop\SimpleCoin\simpleCoin\wallet.py", line 52, in wallet
    check_transactions()
  File "C:\Users\mehan\Desktop\SimpleCoin\simpleCoin\wallet.py", line 88, in check_transactions
    res = requests.get('http://localhost:5000/blocks')
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\mehan\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /blocks (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001748EAAB610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
```
what I have to do ?

**Comment by cosme12** [comment]
May it be possible you have something else running in http://localhost:5000 ?

**Comment by mehanalavimajd** [comment]
No . I don't have any application that use 5000 port

**Comment by cosme12** [comment]
You should be running `miner.py` at the same time.

**Comment by mehanalavimajd** [comment]
How

**Comment by cosme12** [comment]
Right, just open another cmd instance and run `miner.py`. That way you have both scripts running at the same time.

**Comment by mehanalavimajd** [comment]
Thanks 😊
